name: Build & Deploy to E1

on: 
  push:
    branches:
      - develop # Triggers when merging PRs into develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastify-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastify-app:${{ github.sha }}

  deploy: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deployment step
        run: echo "Deploying to E1...(Replace this with actual deployment)"