name: Deploy to E2 (Staging)

on: 
  push:
    branches:
      - release

jobs:
  deploy-to-e2:
    name: Build and Deploy to E2
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout tagged colored
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version_tag }}
      
      - name: Setup Node.js v20.18.1
        uses: actions/setup-node@v4
        with: 
          node-version: v20.18.1
      
      - name: Install Dependencies
        run: npm i

      - name: Run Unit and Integration Tests
        run: npm run test

      - name: Check Code Coverage
        run: npm run coverage
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t fastify-app:${{ github.event.inputs.version_tag }} .

      - name: Push Docker Image
        run: |
          docker push fastify-app:${{ github.event.inputs.version_tag }}
      
      - name: Upload Tag as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-tag
          path: |
            ./

      - name: Deploy to E2
        run: |
          echo "Deploying fastify-app:${{ github.event.inputs.version_tag }} to E2..."