name: Test, Build & Deploy to E2

on: 
  push:
    branches:
      - release/** # Triggers when merging PRs into release branch

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    env:
      TERM: xterm # enables colored and formatted output
    
    strategy:
      matrix:
        node-version: [20.x, 22.x, 23.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environments
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "PORT: $PORT"

      - name: Setup Node.js (${{ matrix.node-version }})
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}
      
      - name: Install Dependencies
        run: npm i
      
      - name: Run Tests
        run: npm run test

      - name: Run Coverage
        run: npm run coverage

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/fastify-app:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/fastify-app:${{ github.sha }}

  deploy: 
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deployment step
        run: echo "Deploying to E2...(Replace this with actual deployment)"
