name: PR Checks

on: 
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    env:
      TERM: xterm # enables colored and formatted output
      PORT: 3000
      HOST: 0.0.0.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js v20.18.1
        uses: actions/setup-node@v4
        with: 
          node-version: v20.18.1
      
      - name: Install Dependencies
        run: npm i
      
      - name: Run Tests
        run: npm run test

      - name: Run Coverage
        run: npm run coverage