name: PR Checks

on: 
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: 20
          cache: 'npm'
      
      - name: Verify Node.js and NPM version
        run: |
          echo "Node.js version: $(node -v)"
          echo "NPM version: $(npm -v)"
      
      - name: Clean npm cache
        run: npm cache clean --force
      
      - name: Install Dependencies
        run: npm i
      
      - name: Run Tests with Environment Variables
        env: 
          PORT: ${{ vars.PORT }}
          HOST: ${{ vars.HOST }}
        run: npm test