name: PR Checks

on: 
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.PORT }}
      HOST: ${{ vars.HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Verify Environment Variables
        run: |
          echo "PORT=$PORT"
          echo "HOST=$HOST"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.18.1'
      
      - name: verify Node.js and npm version
        run: |
          node --version
          npm --version
          echo "******Checking the source code**********"
          pwd
          ls -lrt
      
      - name: build
        uses: actions/setup-node@v4
        with:
        node-version: '20.18.1'
      - run: |
          npm install
      
      - name: Run Tests
        run: npm test