name: PR Checks

on: 
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    env:
      PORT: ${{ vars.PORT }}
      HOST: ${{ vars.HOST }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: amex-eng/setup-node@76c0228676789eff288075b9484735d09200f9f3
        with: 
          node-version: '20.x'
      - run: |
          npm install
      
      - name: Check if jest package exists locally
        run: npm list jest || echo "jest package not found"
        
      - name: Check if fastify package exists locally
        run: npm list fastify || echo "fastify package not found"
      
      - name: Run Tests
        run: npm test