name: PR Checks

on: 
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run Tests & Coverage
    runs-on: ubuntu-latest
    env:
      TERM: xterm # enables colored and formatted output

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Environments
        run: |
          export $(grep -v '^#' .env | xargs)
          echo "PORT: $PORT"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: '20.x'
      
      - name: Install Dependencies
        run: npm i
      
      - name: Run Tests
        run: npm run test

      - name: Run Coverage
        run: npm run coverage